[tool.pyright]
include = ["."]
exclude = ["**/__pycache__", "**/node_modules", "**/.venv", "venv"]
venvPath = "."
venv = "venv"
pythonVersion = "3.13"
typeCheckingMode = "basic"

[tool.pylance]
include = ["."]
exclude = ["**/__pycache__", "**/node_modules", "**/.venv", "venv"]
